language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - flake8 --version

# command to run tests
script: 
  - python setup.py test -q
  - nosetests
  - flake8 pyflakes setup.py

services:
  - redis-server
matrix:
    allow_failures:
        - python: pypy