#include "Kestrel_manager.h"




void Kestrel_manager::clean_pool()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000086A begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000086A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Kestrel_manager::start()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000870 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000870 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Kestrel_manager::clean_tasks()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000090B begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000090B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
