#include "threading.h"




void threading::run()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000876 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000876 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void threading::__bootstrap_inner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087D begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void threading::__bootstrap()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087F begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void threading::stream_event_handler_0()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000889 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000889 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
