#include "xmlstream.h"




void xmlstream::event_runner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000873 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000873 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void xmlstream::run_with_except_hook()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087B begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000087B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void xmlstream::_threaded_event_wrapper()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000088B begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000088B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void xmlstream::process()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000940 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000940 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void xmlstream::connect()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000942 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000942 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Analyze incoming XML stanzas and convert them into stanza
     *  objects if applicable and queue stream events to be processed
     *  by matching handlers.
     */
void xmlstream::__spawn_event()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000962 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000962 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Apply any preprocessing filters.
     */
void xmlstream::incoming_filter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000968 begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:0000000000000968 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Convert the raw XML object into a stanza object. If no registered
     *  stanza type applies, a generic StanzaBase stanza will be used.
     *  @author _build_stanza
     */
void xmlstream::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000096C begin
{
}
// section -64--88-1-2-21a371ae:130e1c8aa65:-8000:000000000000096C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
